### ISSUE TITLE
Multiple `from` values for an account

### ISSUE THREAD

**Issue by 6b6279** [marlam/msmtp#102]
Hello,

I have two aliases over which I would like to send e-mails: One that is anonymized (ex. `010101@my-domain.com`) and one that contains my name (ex. `bob@my-domain.com`). Both of these aliases belong to the same account, i.e. `msmtp` should send e-mails with these addresses in the envelope over the same account, ex. `private`.

For this I have defined the following account in the config file:

```
account private
tls_starttls on
host smtp.my-domain.com
port 587
from bob@my-domain.com
from 010101@my-domain.com
user login
passwordeval "pass show login@my-domain.com"
```

`msmtp` however simply ignores the second `from` entry and tries to send over the default account (which is not `private`). This of course fails.

Is there way to define multiple `from` values for an account? I have read the documentation and I know wildcards can be used, but `*@my-domain.com` wouldn’t work as I have another account with the same host (but different credentials). I also tried listing the possible `from` values in a comma-seperated manner, but that didn’t work either.

Thanks in advance for your help.

**Comment by marlam** [comment]
If you can use a wildcard that only matches the correct subset of mail addresses, then you can choose from that subset with the `-f` option.

You cannot have multiple `from` addresses for the same account, but you could use multiple accounts, e.g.
```
account private
tls_starttls on
host smtp....
pot 587
user ...
from default@...

account private-bob : private
from bob@...

account private-010101 : private
from 010101@...
```
