### ISSUE TITLE
feat: Use From: header as envelope-from 

### ISSUE THREAD

**Issue by WhyNotHugo** [marlam/msmtp#117]
I've a very simple/basic setup to send emails from my desktop via my SMTP:

```
tls on
host smtp.example.com
auth on
user whynothugo@example.com
passwordeval hiq -dFpassword proto=smtp hostname=smtp.example.com username=whynothugo@example.com
domain %h
```

This doesn't quite work with tools that generate and send emails (the first example that comes to mind is `git send-email`.

How, from what I understand, I'd need to configure a new `account` for each different `From` that I use. As far as I can tell, I can use `defaults` to avoid repeating the above block for each one, but I still have to edit the configuration file for each new address/alias.

I wonder what thoughts are on simply using the email address in the `From:` header as the envelope-from as a fallback (e.g.: if nothing else is explicitly specified), even if it's disabled by default.

**Comment by marlam** [comment]
There is the `--read-envelope-from` option, which takes the envelope from address from the `From:` header.

With this option, msmtp chooses a matching account based on this envelope from address. To support more than one envelope from address in a single account definition, you can use wildcards (like in shell filename expansion) in the `from` command in `~/.msmtprc`, for example `from hugo*@example.com` or `from *hugo20??test@example.com`.

**Comment by WhyNotHugo** [comment]
> There is the --read-envelope-from option, which takes the envelope from address from the From: header.

Right, I'd what I'm looking for is a configuration flag that forces the same behavior. I don't usually control the invocation to `sendmail` (e.g.: it gets called by another application like `git` or `mutt`), so I can't just add a flag to the invocation.

**Comment by marlam** [comment]
A workaround could be to set `/usr/sbin/sendmail` to something like this:
```
#!/bin/sh
exec /usr/bin/msmtp --read-envelope-from ... "$@"
```

While it is possible to add a configuration command like `read_envelope_from`, that would have unfortunate interactions with the account choosing mechanism, so I'm not sure if it's worth it.

**Comment by WhyNotHugo** [comment]
> While it is possible to add a configuration command like read_envelope_from, that would have unfortunate interactions with the account choosing mechanism, so I'm not sure if it's worth it.

Wouldn't the above wrapper script have the exact same caveats?

**Comment by WhyNotHugo** [comment]
As an alternative approach, what do you think of the `from` directive having a value like `from header` that sets the envelope from to the same value as the `From:` header?

**Comment by marlam** [comment]
If we added `from header` (or an extra command, e.g. `read_envelope_from on`), then this would only be useful if msmtp knows which account to use via some way other than automatic account selection (i.e. either `--account` or `--host`, or if both are unused: account `default`). Because the new command only applies after the account was chosen.
So it would not work the same way as `--read-envelope-from`. That would probably become confusing.

**Comment by marlam** [comment]
Thanks for these comments. I'll close this issue now since I see no way to add this functionality without breaking something.

**Comment by WhyNotHugo** [comment]
I'm revisiting msmtp as an option, and I have hit this caveat again.

I understand that a `read_envelope_from` configuration flag might not be a great fit for situations where multiple SMTP accounts are being used. But it's extremely useful for the most obvious and simple case: using a single SMTP account.

It looks like right now the alternative "configuration" mechanism to to put the following in `/usr/sbin/sendmail`:

```sh
#!/bin/sh
exec /usr/bin/msmtp --read-envelope-from ... "$@"
```

Honestly, this sounds like a hack. Is this really better design than having a configuration flag to default to this behaviour?

**Comment by merv4** [comment]
@marlam I don't think an exact rendition of `--read-envelope-from` is being asked for. Please correct me if I am misunderstanding.

I think users want a way for the selected profile (via --account, --host, or default) to use "message-header From:" as "envelope-from" **no matter what**. The exact opposite of `set_from_header on`, as @balejk has said.

There is no concept of a correct profile in this case, as it should happen no matter what. There also is no need for this to be account-independent, as it should happen no matter what.

It would likely be more appropriate to call this a mode of `set_from_header`, as in `set_from_header spoof`; this is admittedly a terrible name, but gets the concept across.

P.S. Another naming scheme could be `set_from_header auto|envelope|message|off`; where `on` is deprecated and linked to `envelope`.

**Comment by marlam** [comment]
You can now use `from %F` in your configuration, where `%F` is always replaced with the address extracted from the From header (or Resent-From, if present).
