### ISSUE TITLE
ENV Variables in /etc/msmtp config

### ISSUE THREAD

**Issue by michaelaguiar** [marlam/msmtp#144]
Is it possible to use ENV variables in the `/etc/msmtp` configuration file? It doesn't look like it, but wanted to make sure as this method would be ideal for injecting my config.

For example:
```
defaults
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile -

account default_account
host ${MSMTP_RELAY_SERVER_HOST}
port ${MSMTP_RELAY_SERVER_PORT}
auth ${MSMTP_RELAY_SERVER_AUTH}
user ${MSMTP_RELAY_SERVER_USER}
password ${MSMTP_RELAY_SERVER_PASSWORD}
from ${MSMTP_RELAY_SERVER_FROM}

account default : default_account

```

**Comment by marlam** [comment]
You can use environment variables via the `eval` command.

This command replaces the `eval <command>` line with the output of `command`. For example:

```
eval echo host ${MSMTP_RELAY_SERVER_HOST}
```
