### ISSUE TITLE
support mailx command options "-s"

### ISSUE THREAD

**Issue by greenpdx** [marlam/msmtp#152]
I am trying using smstp to email logs from logrotate.  logrotate expects mailx options, like "-s" for subject. 

even a bash script that calls msmtp would be good
the command line passed is 
-s subject email

**Comment by greenpdx** [comment]
#!/bin/bash
echo -e "\n$2\n$(</dev/stdin)\n" | msmtp $3

This get the data with the first line as subject.

I would like the subject filled in

**Comment by greenpdx** [comment]
echo -e "Subject: $2\n\n$(</dev/stdin)\n" | msmtp $3
 Adds the subject but the "to" email is empty but uses bcc: to deliver the email

**Comment by greenpdx** [comment]
Write file /usr/bin/mai

'''
#!/bin/bash
echo -e "To: $3\nSubject: $2\n\n$(</dev/stdin)\n" | msmtp $3
'''

Please add to documentation.

**Comment by marlam** [comment]
Msmtp does not replace `mailx` or other variants of `mail`. It replaces the `/usr/sbin/sendmail` interface.
That means it does not construct mail (with Subject header etc), it just sends mail.
Typically `mailx` (or similar) is used to construct the mail, and is configured to call msmtp to then send it.
