### ISSUE TITLE
Compile or download 

### ISSUE THREAD

**Issue by tothjsz** [marlam/msmtp#154]
Hi!

How can I compile this software in Windows?
Or where from can I download it as a Win32 application?

Thanks in advnace!

Regards,
Szabolcs

**Comment by marlam** [comment]
Some third-party sites provide Windows packages of msmtp:
* [MSYS2 msmtp package](https://packages.msys2.org/package/mingw-w64-x86_64-msmtp?repo=mingw64)
* [Cygwin msmtp package](https://cygwin.com/packages/summary/msmtp-src.html)
* [Chocolateley msmtp package](https://community.chocolatey.org/packages/msmtp.portable)

To compile yourself, use [MinGW-w64](https://www.mingw-w64.org/), or build a Windows binary on Linux with [MXE](https://mxe.cc/).
