### ISSUE TITLE
Add support for GNOME keyring

### ISSUE THREAD

**Issue by thesp0nge** [marlam/msmtp#160]
Storing password in msmtprc is not a good choice in 2024 where people save their dotfiles in cloud to simplify setup, or just because it's not good having a password in a cleartext file.

Why not adding support for external password managers like GNOME keychain?

**Comment by dnebauer** [comment]
According to the current msmtp documentation `gnome-keyring` is already supported as an authentication method. See [https://marlam.de/msmtp/msmtp.html#Authentication](https://marlam.de/msmtp/msmtp.html#Authentication) for instructions and further details.
