### ISSUE TITLE
-F option stopped working after version 1.8.24

### ISSUE THREAD

**Issue by peos3** [marlam/msmtp#165]
First of all: I am using a dockerized version of msmtp (but I hope this has nothing to do with the issue).

I previously used version 1.8.23 to automatically send E-Mails from my server using the following command:
```
msmtp -F '<FULL_NAME>' <DESTINATION_ADDRESS> <<< '<CONTENT>'
```

Unfortunatly after updating to version 1.8.24 or higher the `FULL_NAME` no longer appears and is therefore missing from the header.

After reading the documentation I found out about the new `from_full_name` command. Adding this option to the configuration file seems to work. Unfortunately the introduction of this command somehow broke the `-F` command line option for me.

**Comment by marlam** [comment]
Thank you for this report. Yes I accidentally broke the -F option, sorry for that. It's fixed now.
