### ISSUE TITLE
libgnutls-dev not found Ubuntu 24

### ISSUE THREAD

**Issue by abletec** [marlam/msmtp#172]
When trying to build msmtp from source the libgnutls-dev could not be located.

**Comment by marlam** [comment]
We'll need a complete error message to see what's going on. Also, please make sure that the package is installed.

**Comment by abletec** [comment]
& that's precisely the point--that particular package is no longer
available to install on Ubuntu 24.
Jackie McBride
Proofpoint Certified Email Authentication Specialist 2024
Author 36: Last Hours of a Life
Be a hero. Fight Scams. Learn how at www.scam911.org/
Also check out wp4newbs.com brightstarsweb.com mysitesbeenhacked.com

**Comment by mlt** [comment]
```
sudo apt install libgnutls28-dev
```

**Comment by abletec** [comment]
Mikhail, thank you so much! I had seen that, but wasn't sure it referenced
an equivalent or nearly equivalent package. Perhaps something in the
instructions to clarify that would be helpful.


Jackie McBride
Proofpoint Certified Email Authentication Specialist 2024
Author 36: Last Hours of a Life
Be a hero. Fight Scams. Learn how at www.scam911.org/
Also check out wp4newbs.com brightstarsweb.com mysitesbeenhacked.com
