### ISSUE TITLE
`logfile_time_format`: unset the log file time format

### ISSUE THREAD

**Issue by NeverWise** [marlam/msmtp#174]
Hi,
I don't know how to unset the log file time format without receiving the error `cannot log to -: invalid logfile_time_format`.
I would like to remove the date and time when logging in stdout or stderr, but it seems that this is only possible when logging to a file.
Thanks in advance

**Comment by marlam** [comment]
Should be fixed now: Use `logfile_time_format none`. This is not ideal, but reinterpreting an empty argument as an empty format string might break existing configurations.
