### ISSUE TITLE
test scripts are not packaged in distribution file

### ISSUE THREAD

**Issue by bwarden** [marlam/msmtp#175]
The following files under the tests directory are missing from the distribution tarball https://marlam.de/msmtp/releases/msmtp-1.8.27.tar.xz:
* tests/test-auth-plain.sh
* tests/test-basic.sh
* tests/test-header-handling.sh

**Comment by marlam** [comment]
This was already fixed [here](https://github.com/marlam/msmtp/commit/2534708a094d5ee18876d31a0c9d856a0e15a3fe).
