### ISSUE TITLE
tmp dir location

### ISSUE THREAD

**Issue by EvgenijKrupchenko** [marlam/msmtp#178]
I'm trying to run msmtp in a multi-user environment, where all users have their own tmp dir. And system /tmp is set to 000 mode.
And i see no way to run it like that.
Your manual says:

Environment TMPDIR - Directory to create temporary files in. If this is unset, a system specific
default directory is used

But it is completely ignored! I also got the source codes and also there's no place of using that env var.
Only tmpfile() call, which don't use TMPDIR
So? Why not just add a config variable or some key like msmtp --tmp=/path/to/tmp

**Comment by marlam** [comment]
Yes, the `TMPDIR` entry in the documentation is wrong -- it's a leftover from before switching to `tmpfile()` and should be removed (in fact I just did that).

So yes, there is currently no way to specify a directory for temporary files.

But I don't think adding yet another configuration option is the right solution.

Using mount namespaces allows to have per-user tmp directories mounted at `/tmp` - this will automatically fix your problem, and it works with all programs that use the standard `tmpfile()` function. `pam_namespace` can do that for you.
