### ISSUE TITLE
[FEAT] Add dry-run option

### ISSUE THREAD

**Issue by avidseeker** [marlam/msmtp#179]
It might be preferable to preview the message sent to the server verbatim. E.g: check for headers, X-Mailer, look for IP leaks, etc. Having a `--dry` option to do that would also solve the commonly requested feature which is saving sent mail to a directory. (Just websearch the keywords "msmtp save to sent". Here's a [SE question](https://superuser.com/questions/683535/).)

E.g:

```
msmtp --dry test@example.com < mail.txt > ~/Sent/mail.eml
```

**Comment by marlam** [comment]
For debugging purposes, you can use the following:
```
msmtpd --interface=::1 --port=12345 --command='cat; echo'
```
That will dump the mail (`cat`) and the command line (`echo`) to stdout whenusing msmtp like this:
```
msmtp --host=::1 --port=12345 --from test@example.com recipient@example.com < mail.txt
```

Saving a copy of a mail to a `sent-mail` folder is the responsibility of the mail user agent, not msmtp.

**Comment by avidseeker** [comment]
> Saving a copy of a mail to a sent-mail folder is the responsibility of the mail user agent, not msmtp.

Using MUA works when I'm sending email through the MUA TUI, but not when sending email through CLI. Not all MUA support CLI usage (e.g: [aerc](https://lists.sr.ht/~rjarry/aerc-discuss/%3CEeSvMG6vefIamInYgP4FCx1st0PWXktMp7OZnpXeX3bVblSI5obDIrqtE7T8FEofC2lFXLQkKP_UYAv1-Fx_tDcf3yXhrFPT09N4jMPWIy4=@protonmail.com%3E)).

```
$ weekly_mail_cronjob | msmtp mailing@list.org    # I want a copy of that in my +Sent
```

**Comment by marlam** [comment]
This is not how msmtp (or any sendmail compatible program) is supposed to be used. You don't pipe the output of some random command directly into it. You need to use a program that can construct a valid mail. And that program can then also save a copy of the mail.

**Comment by avidseeker** [comment]
On Wed Dec 25, 2024 at 11:13 PM PST, Martin Lambers wrote:
> You need to use a program that can construct a valid mail.

Such as? aerc as I said doesn't provide CLI usage for the feature I'm
looking for. mutt/neomutt seems like an overkill setup for such a simple cron task.

> ... a program that can construct a valid mail

But isn't this what msmtp does? It takes the body of the email from a
random script and wraps it with the proper headers and sends it.

-- Avidus

**Comment by marlam** [comment]
> On Wed Dec 25, 2024 at 11:13 PM PST, Martin Lambers wrote: You need to use a program that can construct a valid mail.
> Such as? aerc as I said doesn't provide CLI usage for the feature I'm looking for. mutt/neomutt seems like an overkill setup for such a simple cron task.

There should be a `/usr/bin/mail` program, for example from the mailx or bsd-mailx or s-nail package, depending on your platform. That's the MUA (mail user agent): it creates mails and typically sends them via `/usr/sbin/sendmail` (which might be provided by postfix or exim or msmtp or something else).

> ... a program that can construct a valid mail
> But isn't this what msmtp does? It takes the body of the email from a random script and wraps it with the proper headers and sends it.

No, msmtp (or any other sendmail-compatible program) takes a full mail and sends it, not just a mail body. The complete mail must be created first, by some MUA (not necessarily `/usr/bin/mail`).
