### ISSUE TITLE
1.8.27 fails to build: `error: 'GSASL_CB_TLS_EXPORTER' undeclared (first use in this function); did you mean 'GSASL_CB_TLS_UNIQUE'?`

### ISSUE THREAD

**Issue by barracuda156** [marlam/msmtp#182]
```
smtp.c: In function 'smtp_auth':
smtp.c:1392:19: error: 'GSASL_CB_TLS_EXPORTER' undeclared (first use in this function); did you mean 'GSASL_CB_TLS_UNIQUE'?
 1392 |                 ? GSASL_CB_TLS_EXPORTER : GSASL_CB_TLS_UNIQUE,
      |                   ^~~~~~~~~~~~~~~~~~~~~
      |                   GSASL_CB_TLS_UNIQUE
smtp.c:1392:19: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [smtp.o] Error 1
```

**Comment by barracuda156** [comment]
@marlam Could you please take a look? The coded added in https://github.com/marlam/msmtp/commit/e9ae256f457739b5995ad4784d92fadc05cdcef4 and a fix added in https://github.com/marlam/msmtp/commit/f789ee168f5bf9aef7dd5d627d78f5756c528743 but it still fails to compile in some cases.
Here, apparently, TLS 1.2 is supported in gsasl, but not 1.3.

**Comment by marlam** [comment]
Please simply use a non-ancient version of GNU SASL, i.e. >= 2.1.0.

**Comment by barracuda156** [comment]
> Please simply use a non-ancient version of GNU SASL, i.e. >= 2.1.0.

Well, MacPorts is at 1.10.0 for some reason, I opened a ticket to update it: https://trac.macports.org/ticket/71521

(Locally I can fix it for myself, of course, but it does not solve the issue for everyone else.)
